//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviationManager.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviationManager.Lang.language_en", typeof(language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Failed..
        /// </summary>
        internal static string actionFailed {
            get {
                return ResourceManager.GetString("actionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Approve And Reject At The Same Time!!.
        /// </summary>
        internal static string alertApprovedRejected {
            get {
                return ResourceManager.GetString("alertApprovedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Approvement Was Already Done, You Can Not Change IT !.
        /// </summary>
        internal static string alertApprovementAlreadyDone {
            get {
                return ResourceManager.GetString("alertApprovementAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Deviation Means You Will Not Be Able Later To Make Any Change On It, Are You Sure You Wish To Make This Action ?.
        /// </summary>
        internal static string alertCloseDeviation {
            get {
                return ResourceManager.GetString("alertCloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Sure, You Wish to Delete This Approvement Group?.
        /// </summary>
        internal static string alertDeleteApprovementGroup {
            get {
                return ResourceManager.GetString("alertDeleteApprovementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Sure, You Wish to Delete This Attachment ?.
        /// </summary>
        internal static string alertDeleteAttachment {
            get {
                return ResourceManager.GetString("alertDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and You must Reject or Approve the Deviation.
        /// </summary>
        internal static string alertDeviationValidation {
            get {
                return ResourceManager.GetString("alertDeviationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in text detected.
        /// </summary>
        internal static string alertInvalidTextEntered {
            get {
                return ResourceManager.GetString("alertInvalidTextEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action.
        /// </summary>
        internal static string alertNoAccess {
            get {
                return ResourceManager.GetString("alertNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        internal static string alertNoItemSelected {
            get {
                return ResourceManager.GetString("alertNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Programm Use Outlock Service To Send Your Email, You Need To Execute Outlock First Than Send Your Email..
        /// </summary>
        internal static string alertOutlookNotRunning {
            get {
                return ResourceManager.GetString("alertOutlookNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Make This Action Now, You Schould First Save The Deviation !.
        /// </summary>
        internal static string alertSaveDeviationFirst {
            get {
                return ResourceManager.GetString("alertSaveDeviationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Text field(s) cannot be empty.
        /// </summary>
        internal static string alertTextboxEmpty {
            get {
                return ResourceManager.GetString("alertTextboxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvement Group was successfully added!.
        /// </summary>
        internal static string approvementAdded {
            get {
                return ResourceManager.GetString("approvementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Approvement Was Succesfuly Done !.
        /// </summary>
        internal static string approvementDone {
            get {
                return ResourceManager.GetString("approvementDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvement Group was successfully updated!.
        /// </summary>
        internal static string approvementUpdated {
            get {
                return ResourceManager.GetString("approvementUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose a Deviation Before making this Action!.
        /// </summary>
        internal static string chooseDeviation {
            get {
                return ResourceManager.GetString("chooseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete Deviation.
        /// </summary>
        internal static string deleteDeviation {
            get {
                return ResourceManager.GetString("deleteDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Was Successfuly Added.
        /// </summary>
        internal static string deviationAdded {
            get {
                return ResourceManager.GetString("deviationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Make Any Change On This Item Because Its Already Closed !.
        /// </summary>
        internal static string deviationAlreadyClosed {
            get {
                return ResourceManager.GetString("deviationAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Period Has Not Valid Inputs !, The Input &lt;&lt;P.Second date&gt;&gt; Must Be Bigger Than the Input &lt;&lt;P.First date&gt;&gt;.
        /// </summary>
        internal static string deviationNegativePeriod {
            get {
                return ResourceManager.GetString("deviationNegativePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Does Not Exist..
        /// </summary>
        internal static string deviationNotExist {
            get {
                return ResourceManager.GetString("deviationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Period Has Not To Be Null!, You Can Choose Different Dates To Avoid This..
        /// </summary>
        internal static string deviationPeriodNull {
            get {
                return ResourceManager.GetString("deviationPeriodNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Was Successfly Updated..
        /// </summary>
        internal static string deviationupdated {
            get {
                return ResourceManager.GetString("deviationupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Was Succesfuly Expired..
        /// </summary>
        internal static string deviationWasClosed {
            get {
                return ResourceManager.GetString("deviationWasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Email has been sent !.
        /// </summary>
        internal static string emailSent {
            get {
                return ResourceManager.GetString("emailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / Anlage :.
        /// </summary>
        internal static string emailSubjectLine {
            get {
                return ResourceManager.GetString("emailSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deviation for the Line:.
        /// </summary>
        internal static string emailSubjectNewDeviationLine {
            get {
                return ResourceManager.GetString("emailSubjectNewDeviationLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deviation for the product : .
        /// </summary>
        internal static string emailSubjectNewDeviationProduct {
            get {
                return ResourceManager.GetString("emailSubjectNewDeviationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, The Deviation Cloud Not Be Expired..
        /// </summary>
        internal static string errorCloseDeviation {
            get {
                return ResourceManager.GetString("errorCloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros, The Email Was Not Sent Try Again !.
        /// </summary>
        internal static string errorSendEmail {
            get {
                return ResourceManager.GetString("errorSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This File Dos Not Exist Any More!..
        /// </summary>
        internal static string fileNotExist {
            get {
                return ResourceManager.GetString("fileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Had Been Removed From The List!..
        /// </summary>
        internal static string fileRemovedFromList {
            get {
                return ResourceManager.GetString("fileRemovedFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Form Inputs Are Not Valid !.
        /// </summary>
        internal static string formInputsNotValid {
            get {
                return ResourceManager.GetString("formInputsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Form.
        /// </summary>
        internal static string formInvalid {
            get {
                return ResourceManager.GetString("formInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs Are Missing !!.
        /// </summary>
        internal static string inputsMissing {
            get {
                return ResourceManager.GetString("inputsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Inputs Are Required ..
        /// </summary>
        internal static string inputsRequired {
            get {
                return ResourceManager.GetString("inputsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string inValid {
            get {
                return ResourceManager.GetString("inValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item was Successfuly Deleted.
        /// </summary>
        internal static string itemDeleted {
            get {
                return ResourceManager.GetString("itemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Item To Delete, You Should First Choose The Item To Delete!.
        /// </summary>
        internal static string itemDeleteError {
            get {
                return ResourceManager.GetString("itemDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ladd {
            get {
                return ResourceManager.GetString("ladd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Deviation.
        /// </summary>
        internal static string laddDeviation {
            get {
                return ResourceManager.GetString("laddDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Deviation.
        /// </summary>
        internal static string laddNewDeviation {
            get {
                return ResourceManager.GetString("laddNewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Identification Method .
        /// </summary>
        internal static string lalternativeIdMethod {
            get {
                return ResourceManager.GetString("lalternativeIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvement.
        /// </summary>
        internal static string lapprovement {
            get {
                return ResourceManager.GetString("lapprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string lapprovementConfirm {
            get {
                return ResourceManager.GetString("lapprovementConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save your Change, click confirm Button!..
        /// </summary>
        internal static string lapprovementLightGreenMsg {
            get {
                return ResourceManager.GetString("lapprovementLightGreenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To approve or reject this Deviation you need first to save it..
        /// </summary>
        internal static string lapprovementLightRedMsg {
            get {
                return ResourceManager.GetString("lapprovementLightRedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Deviation.
        /// </summary>
        internal static string lclose {
            get {
                return ResourceManager.GetString("lclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Deviation.
        /// </summary>
        internal static string lcloseDeviation {
            get {
                return ResourceManager.GetString("lcloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created In.
        /// </summary>
        internal static string lcreatedIn {
            get {
                return ResourceManager.GetString("lcreatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ldate {
            get {
                return ResourceManager.GetString("ldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date 1.
        /// </summary>
        internal static string ldate1 {
            get {
                return ResourceManager.GetString("ldate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date 2.
        /// </summary>
        internal static string ldate2 {
            get {
                return ResourceManager.GetString("ldate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ldateCreation {
            get {
                return ResourceManager.GetString("ldateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ldelete {
            get {
                return ResourceManager.GetString("ldelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ldescription {
            get {
                return ResourceManager.GetString("ldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Description of Deviation.
        /// </summary>
        internal static string ldetailDescOfDev {
            get {
                return ResourceManager.GetString("ldetailDescOfDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Request Condition.
        /// </summary>
        internal static string ldetailRequestCondition {
            get {
                return ResourceManager.GetString("ldetailRequestCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Deviation is expired, you can not approve or accept it!.
        /// </summary>
        internal static string ldeviationexpiredChange {
            get {
                return ResourceManager.GetString("ldeviationexpiredChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Infos.
        /// </summary>
        internal static string lDeviationInfo {
            get {
                return ResourceManager.GetString("lDeviationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation List.
        /// </summary>
        internal static string ldeviationList {
            get {
                return ResourceManager.GetString("ldeviationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation No.
        /// </summary>
        internal static string ldeviationNo {
            get {
                return ResourceManager.GetString("ldeviationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Type.
        /// </summary>
        internal static string ldeviationType {
            get {
                return ResourceManager.GetString("ldeviationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document was created automatically and is valid without signature. Application: DeviationManager, Version 1.0.
        /// </summary>
        internal static string ldigitalSignature {
            get {
                return ResourceManager.GetString("ldigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ldowload {
            get {
                return ResourceManager.GetString("ldowload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Deviation.
        /// </summary>
        internal static string leditDeviation {
            get {
                return ResourceManager.GetString("leditDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lemail {
            get {
                return ResourceManager.GetString("lemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Deviations.
        /// </summary>
        internal static string lfilterDeviation {
            get {
                return ResourceManager.GetString("lfilterDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lid {
            get {
                return ResourceManager.GetString("lid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string lmachine {
            get {
                return ResourceManager.GetString("lmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deviation.
        /// </summary>
        internal static string lnewDeviation {
            get {
                return ResourceManager.GetString("lnewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other( Optional).
        /// </summary>
        internal static string loptional {
            get {
                return ResourceManager.GetString("loptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string lothers {
            get {
                return ResourceManager.GetString("lothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGIONAL QUALITY DIRECTOR APPROVAL:  REFER TO FTDS-BM-P-008  FOR REQUIREMENT.
        /// </summary>
        internal static string lothersBox1 {
            get {
                return ResourceManager.GetString("lothersBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT ENGINEERING APPROVAL:  REFER TO FTDS-BM-P-008  FOR REQUIREMENT.
        /// </summary>
        internal static string lothersBox2 {
            get {
                return ResourceManager.GetString("lothersBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUFACTURING ENGINEERING APPROVAL:  REFER TO FTDS-BM-P-008  FOR REQUIREMENT..
        /// </summary>
        internal static string lothersBox3 {
            get {
                return ResourceManager.GetString("lothersBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER APPROVAL:  REFER TO FTDS-BM-P-008  FOR REQUIREMENT.
        /// </summary>
        internal static string lothersBox4 {
            get {
                return ResourceManager.GetString("lothersBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Begin .
        /// </summary>
        internal static string lperiodBegin {
            get {
                return ResourceManager.GetString("lperiodBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Period.
        /// </summary>
        internal static string lperiodDevation {
            get {
                return ResourceManager.GetString("lperiodDevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period End.
        /// </summary>
        internal static string lperiodEnd {
            get {
                return ResourceManager.GetString("lperiodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lposition {
            get {
                return ResourceManager.GetString("lposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Deviation.
        /// </summary>
        internal static string lprint {
            get {
                return ResourceManager.GetString("lprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lproduct {
            get {
                return ResourceManager.GetString("lproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref.
        /// </summary>
        internal static string lref {
            get {
                return ResourceManager.GetString("lref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Group.
        /// </summary>
        internal static string lremindGroup {
            get {
                return ResourceManager.GetString("lremindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Approved.
        /// </summary>
        internal static string lrequestApproved {
            get {
                return ResourceManager.GetString("lrequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        internal static string lrequestedBy {
            get {
                return ResourceManager.GetString("lrequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Rejeceted.
        /// </summary>
        internal static string lrequestedRejected {
            get {
                return ResourceManager.GetString("lrequestedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Category.
        /// </summary>
        internal static string lriskCategory {
            get {
                return ResourceManager.GetString("lriskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (X=?,Y=?), X correspond to  &quot;Einfluss der Produktqualität&quot;; Y correspond to  &quot; Wahrscheinlichkeit der Entdeckung&quot;..
        /// </summary>
        internal static string lriskMatrixInfo {
            get {
                return ResourceManager.GetString("lriskMatrixInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lrole {
            get {
                return ResourceManager.GetString("lrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Deviation.
        /// </summary>
        internal static string lsave {
            get {
                return ResourceManager.GetString("lsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please select the deviation type--.
        /// </summary>
        internal static string lselectItem {
            get {
                return ResourceManager.GetString("lselectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string lshow {
            get {
                return ResourceManager.GetString("lshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Deviation.
        /// </summary>
        internal static string lshowDeviation {
            get {
                return ResourceManager.GetString("lshowDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string lsignature {
            get {
                return ResourceManager.GetString("lsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standad Condition.
        /// </summary>
        internal static string lstandardCondition {
            get {
                return ResourceManager.GetString("lstandardCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string lsticPrint {
            get {
                return ResourceManager.GetString("lsticPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lupdate {
            get {
                return ResourceManager.GetString("lupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use All Inputs.
        /// </summary>
        internal static string luseAllInputs {
            get {
                return ResourceManager.GetString("luseAllInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why.
        /// </summary>
        internal static string lwhy {
            get {
                return ResourceManager.GetString("lwhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Why to schow reason change for deviation.
        /// </summary>
        internal static string lwhyBox {
            get {
                return ResourceManager.GetString("lwhyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Make Any Change On This Item Because Its Already Expired !.
        /// </summary>
        internal static string notAllowedToChange {
            get {
                return ResourceManager.GetString("notAllowedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Update This Item !.
        /// </summary>
        internal static string notAllowedToUpdateItem {
            get {
                return ResourceManager.GetString("notAllowedToUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed.
        /// </summary>
        internal static string passwordChanged {
            get {
                return ResourceManager.GetString("passwordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been NOT changed.
        /// </summary>
        internal static string passwordChangeFailed {
            get {
                return ResourceManager.GetString("passwordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong.
        /// </summary>
        internal static string passwordWrong {
            get {
                return ResourceManager.GetString("passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose A Directory To Save Your File.
        /// </summary>
        internal static string saveFileDialog {
            get {
                return ResourceManager.GetString("saveFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Select a Line Before making this Action!.
        /// </summary>
        internal static string selectLine {
            get {
                return ResourceManager.GetString("selectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
    }
}
