//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviationManager.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviationManager.Lang.language_de", typeof(language_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlgeschlagen.
        /// </summary>
        internal static string actionFailed {
            get {
                return ResourceManager.GetString("actionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können nicht zur gleichen Zeit freigeben und ablehnen.
        /// </summary>
        internal static string alertApprovedRejected {
            get {
                return ResourceManager.GetString("alertApprovedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereits Freigegeben, Änderungen sind nicht mehr möglich.
        /// </summary>
        internal static string alertApprovementAlreadyDone {
            get {
                return ResourceManager.GetString("alertApprovementAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung zu sperren bedeutet, dass Sie keine Aktionen mehr durchführen können. Sind Sie sicher?.
        /// </summary>
        internal static string alertCloseDeviation {
            get {
                return ResourceManager.GetString("alertCloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie löschen möchten?.
        /// </summary>
        internal static string alertDeleteApprovementGroup {
            get {
                return ResourceManager.GetString("alertDeleteApprovementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie diesen Anhang löschen möchten?.
        /// </summary>
        internal static string alertDeleteAttachment {
            get {
                return ResourceManager.GetString("alertDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Bitte die Abweichung Freigeben oder Ablehnen.
        /// </summary>
        internal static string alertDeviationValidation {
            get {
                return ResourceManager.GetString("alertDeviationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Zeichen im Text gefunden.
        /// </summary>
        internal static string alertInvalidTextEntered {
            get {
                return ResourceManager.GetString("alertInvalidTextEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind nicht berechtigt, diese Aktion durchzuführen.
        /// </summary>
        internal static string alertNoAccess {
            get {
                return ResourceManager.GetString("alertNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Auswahl getroffen.
        /// </summary>
        internal static string alertNoItemSelected {
            get {
                return ResourceManager.GetString("alertNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programm benötigt Outlook zum Versenden der Email, bitte starten Sie Outlook.exe.
        /// </summary>
        internal static string alertOutlookNotRunning {
            get {
                return ResourceManager.GetString("alertOutlookNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen sind nicht möglich, bitte speichern Sie zuerst die Abweichung.
        /// </summary>
        internal static string alertSaveDeviationFirst {
            get {
                return ResourceManager.GetString("alertSaveDeviationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pflichfelder müssen gefüllt werden.
        /// </summary>
        internal static string alertTextboxEmpty {
            get {
                return ResourceManager.GetString("alertTextboxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Gruppe wurde erfolgreich hinzugefügt.
        /// </summary>
        internal static string approvementAdded {
            get {
                return ResourceManager.GetString("approvementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe erfolgreich.
        /// </summary>
        internal static string approvementDone {
            get {
                return ResourceManager.GetString("approvementDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Gruppe wurde erfolgreich aktualisiert.
        /// </summary>
        internal static string approvementUpdated {
            get {
                return ResourceManager.GetString("approvementUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Abweichung, bevor Sie weitere Aktionen durchführen.
        /// </summary>
        internal static string chooseDeviation {
            get {
                return ResourceManager.GetString("chooseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung löschen.
        /// </summary>
        internal static string deleteDeviation {
            get {
                return ResourceManager.GetString("deleteDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung wurde erfolgreich hinzugefügt.
        /// </summary>
        internal static string deviationAdded {
            get {
                return ResourceManager.GetString("deviationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen nicht mehr möglich, da die Abweichung bereits gesperrt wurde.
        /// </summary>
        internal static string deviationAlreadyClosed {
            get {
                return ResourceManager.GetString("deviationAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsperiode ungültig, Eingabe &lt;&lt;P.Second date&gt;&gt; muss grösser sein als Abweichungsperiode &lt;&lt;P.First date&gt;&gt;.
        /// </summary>
        internal static string deviationNegativePeriod {
            get {
                return ResourceManager.GetString("deviationNegativePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung nicht vorhanden.
        /// </summary>
        internal static string deviationNotExist {
            get {
                return ResourceManager.GetString("deviationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsperiode darf nicht leer sein, bitte wählen Sie eine entsprechende Abweichungsperiode.
        /// </summary>
        internal static string deviationPeriodNull {
            get {
                return ResourceManager.GetString("deviationPeriodNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung erfolgreich aktualisiert.
        /// </summary>
        internal static string deviationupdated {
            get {
                return ResourceManager.GetString("deviationupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung wurde erfolgreich gesperrt.
        /// </summary>
        internal static string deviationWasClosed {
            get {
                return ResourceManager.GetString("deviationWasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email versendet.
        /// </summary>
        internal static string emailSent {
            get {
                return ResourceManager.GetString("emailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / Anlage :.
        /// </summary>
        internal static string emailSubjectLine {
            get {
                return ResourceManager.GetString("emailSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Abweichung für die Anlage :.
        /// </summary>
        internal static string emailSubjectNewDeviationLine {
            get {
                return ResourceManager.GetString("emailSubjectNewDeviationLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Abweichung für das Produkt :.
        /// </summary>
        internal static string emailSubjectNewDeviationProduct {
            get {
                return ResourceManager.GetString("emailSubjectNewDeviationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler, die Abweichung konnte nicht gesperrt werden.
        /// </summary>
        internal static string errorCloseDeviation {
            get {
                return ResourceManager.GetString("errorCloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler, die Email konnte nicht versendet werden, bitte versuchen Sie es erneut.
        /// </summary>
        internal static string errorSendEmail {
            get {
                return ResourceManager.GetString("errorSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei nicht mehr vorhanden.
        /// </summary>
        internal static string fileNotExist {
            get {
                return ResourceManager.GetString("fileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei wurde aus der Liste entfernt.
        /// </summary>
        internal static string fileRemovedFromList {
            get {
                return ResourceManager.GetString("fileRemovedFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingaben ungültig.
        /// </summary>
        internal static string formInputsNotValid {
            get {
                return ResourceManager.GetString("formInputsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ungültiges Formular.
        /// </summary>
        internal static string formInvalid {
            get {
                return ResourceManager.GetString("formInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingaben fehlen.
        /// </summary>
        internal static string inputsMissing {
            get {
                return ResourceManager.GetString("inputsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingaben benötigt.
        /// </summary>
        internal static string inputsRequired {
            get {
                return ResourceManager.GetString("inputsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültig.
        /// </summary>
        internal static string inValid {
            get {
                return ResourceManager.GetString("inValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich gelöscht.
        /// </summary>
        internal static string itemDeleted {
            get {
                return ResourceManager.GetString("itemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen nicht möglich, bitte treffen Sie zuerst eine Auswahl.
        /// </summary>
        internal static string itemDeleteError {
            get {
                return ResourceManager.GetString("itemDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string ladd {
            get {
                return ResourceManager.GetString("ladd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung erstellen.
        /// </summary>
        internal static string laddDeviation {
            get {
                return ResourceManager.GetString("laddDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle eine Abweichungserlaubnis.
        /// </summary>
        internal static string laddNewDeviation {
            get {
                return ResourceManager.GetString("laddNewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhang.
        /// </summary>
        internal static string lalternativeIdMethod {
            get {
                return ResourceManager.GetString("lalternativeIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe.
        /// </summary>
        internal static string lapprovement {
            get {
                return ResourceManager.GetString("lapprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        internal static string lapprovementConfirm {
            get {
                return ResourceManager.GetString("lapprovementConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um Ihre Änderungen zu speichern, klicken Sie auf Bestätigen..
        /// </summary>
        internal static string lapprovementLightGreenMsg {
            get {
                return ResourceManager.GetString("lapprovementLightGreenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um diese Abweichung freizugeben/ablehen, muss sie erst gespeichert werden..
        /// </summary>
        internal static string lapprovementLightRedMsg {
            get {
                return ResourceManager.GetString("lapprovementLightRedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung.
        /// </summary>
        internal static string lartabweichung {
            get {
                return ResourceManager.GetString("lartabweichung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung sperren.
        /// </summary>
        internal static string lclose {
            get {
                return ResourceManager.GetString("lclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung sperren.
        /// </summary>
        internal static string lcloseDeviation {
            get {
                return ResourceManager.GetString("lcloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        internal static string lcreatedIn {
            get {
                return ResourceManager.GetString("lcreatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string ldate {
            get {
                return ResourceManager.GetString("ldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum von.
        /// </summary>
        internal static string ldate1 {
            get {
                return ResourceManager.GetString("ldate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum bis.
        /// </summary>
        internal static string ldate2 {
            get {
                return ResourceManager.GetString("ldate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string ldateCreation {
            get {
                return ResourceManager.GetString("ldateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to löschen.
        /// </summary>
        internal static string ldelete {
            get {
                return ResourceManager.GetString("ldelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string ldescription {
            get {
                return ResourceManager.GetString("ldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaillierte Beschreibung der Abweichung.
        /// </summary>
        internal static string ldetailDescOfDev {
            get {
                return ResourceManager.GetString("ldetailDescOfDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung Istzustand.
        /// </summary>
        internal static string ldetailRequestCondition {
            get {
                return ResourceManager.GetString("ldetailRequestCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Abweichung wurde agelaufen, daher sind diese Änderungen nicht mehr möglich..
        /// </summary>
        internal static string ldeviationexpiredChange {
            get {
                return ResourceManager.GetString("ldeviationexpiredChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung Suchmaske.
        /// </summary>
        internal static string ldeviationFilterBox {
            get {
                return ResourceManager.GetString("ldeviationFilterBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zur Abweichung.
        /// </summary>
        internal static string lDeviationInfo {
            get {
                return ResourceManager.GetString("lDeviationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsliste.
        /// </summary>
        internal static string ldeviationList {
            get {
                return ResourceManager.GetString("ldeviationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung Nr..
        /// </summary>
        internal static string ldeviationNo {
            get {
                return ResourceManager.GetString("ldeviationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art der.
        /// </summary>
        internal static string ldeviationType {
            get {
                return ResourceManager.GetString("ldeviationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Dokument wurde maschinell erstellt und ist ohne Unterschrift gültig. Anwendung: DeviationManager, Version: 1.0.
        /// </summary>
        internal static string ldigitalSignature {
            get {
                return ResourceManager.GetString("ldigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ldowload {
            get {
                return ResourceManager.GetString("ldowload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ldowonloadToolTip {
            get {
                return ResourceManager.GetString("ldowonloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung überarbeiten.
        /// </summary>
        internal static string leditDeviation {
            get {
                return ResourceManager.GetString("leditDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung filtern.
        /// </summary>
        internal static string lfilterDeviation {
            get {
                return ResourceManager.GetString("lfilterDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlage.
        /// </summary>
        internal static string lmachine {
            get {
                return ResourceManager.GetString("lmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Abweichung.
        /// </summary>
        internal static string lnewDeviation {
            get {
                return ResourceManager.GetString("lnewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string loptional {
            get {
                return ResourceManager.GetString("loptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lothers {
            get {
                return ResourceManager.GetString("lothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Regional Quality Director: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox1 {
            get {
                return ResourceManager.GetString("lothersBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Product Engineering: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox2 {
            get {
                return ResourceManager.GetString("lothersBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Manufacturing Engineering (CCC Manager): Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox3 {
            get {
                return ResourceManager.GetString("lothersBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Customer: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox4 {
            get {
                return ResourceManager.GetString("lothersBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginn (der Abweichung).
        /// </summary>
        internal static string lperiodBegin {
            get {
                return ResourceManager.GetString("lperiodBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsdauer.
        /// </summary>
        internal static string lperiodDevation {
            get {
                return ResourceManager.GetString("lperiodDevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende (der Abweichung).
        /// </summary>
        internal static string lperiodEnd {
            get {
                return ResourceManager.GetString("lperiodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lposition {
            get {
                return ResourceManager.GetString("lposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung drucken.
        /// </summary>
        internal static string lprint {
            get {
                return ResourceManager.GetString("lprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string lproduct {
            get {
                return ResourceManager.GetString("lproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezug.
        /// </summary>
        internal static string lref {
            get {
                return ResourceManager.GetString("lref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe erinnern.
        /// </summary>
        internal static string lremindGroup {
            get {
                return ResourceManager.GetString("lremindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfrage genehmigt.
        /// </summary>
        internal static string lrequestApproved {
            get {
                return ResourceManager.GetString("lrequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt von.
        /// </summary>
        internal static string lrequestedBy {
            get {
                return ResourceManager.GetString("lrequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfrage abgelehnt.
        /// </summary>
        internal static string lrequestedRejected {
            get {
                return ResourceManager.GetString("lrequestedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risikokategorie.
        /// </summary>
        internal static string lriskCategory {
            get {
                return ResourceManager.GetString("lriskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (X=?,Y=?), X bezieht sich auf dem Einfluss der Produktqualität; Y bezieht sich auf der Wahrscheinlichkeit der Entdeckung..
        /// </summary>
        internal static string lriskMatrixInfo {
            get {
                return ResourceManager.GetString("lriskMatrixInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung speichern.
        /// </summary>
        internal static string lsave {
            get {
                return ResourceManager.GetString("lsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Bitte wählen Sie die Art der Abweichung--.
        /// </summary>
        internal static string lselectItem {
            get {
                return ResourceManager.GetString("lselectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        internal static string lshow {
            get {
                return ResourceManager.GetString("lshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung anzeigen.
        /// </summary>
        internal static string lshowDeviation {
            get {
                return ResourceManager.GetString("lshowDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterschrift.
        /// </summary>
        internal static string lsignature {
            get {
                return ResourceManager.GetString("lsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung Sollzustand.
        /// </summary>
        internal static string lstandardCondition {
            get {
                return ResourceManager.GetString("lstandardCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        internal static string lsticPrint {
            get {
                return ResourceManager.GetString("lsticPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lupdate {
            get {
                return ResourceManager.GetString("lupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Angaben.
        /// </summary>
        internal static string luseAllInputs {
            get {
                return ResourceManager.GetString("luseAllInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum.
        /// </summary>
        internal static string lwhy {
            get {
                return ResourceManager.GetString("lwhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5  Why um die Ursache des Problems zu finden bzw. aufzuzeigen.
        /// </summary>
        internal static string lwhyBox {
            get {
                return ResourceManager.GetString("lwhyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstiges.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen nicht mehr möglich, da die Abweichung bereits gesperrt wurde.
        /// </summary>
        internal static string notAllowedToChange {
            get {
                return ResourceManager.GetString("notAllowedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind nicht berechtigt die Abweichung zu aktualisieren.
        /// </summary>
        internal static string notAllowedToUpdateItem {
            get {
                return ResourceManager.GetString("notAllowedToUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort erfolgreich geändert.
        /// </summary>
        internal static string passwordChanged {
            get {
                return ResourceManager.GetString("passwordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort nicht geändert.
        /// </summary>
        internal static string passwordChangeFailed {
            get {
                return ResourceManager.GetString("passwordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort falsch.
        /// </summary>
        internal static string passwordWrong {
            get {
                return ResourceManager.GetString("passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte Verzeichnis wählen, um die Datei zu speichern.
        /// </summary>
        internal static string saveFileDialog {
            get {
                return ResourceManager.GetString("saveFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte zuerst Linie auswählen.
        /// </summary>
        internal static string selectLine {
            get {
                return ResourceManager.GetString("selectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig.
        /// </summary>
        internal static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
    }
}
